[lib]
name = "msgpack"

[package]
name = "msgpack-rs"
version = "0.1.0"
authors = ["Yuta Iwama <ganmacs@gmail.com>"]
edition = "2018"

[dependencies]

byteorder = "1"
bytes = { git = "https://github.com/tokio-rs/bytes" }
chrono = "0.4"
